[build]
command = """
rm -rf flutter-sdk &&
git clone https://github.com/flutter/flutter.git --depth 1 -b stable flutter-sdk &&
export PATH="$PWD/flutter-sdk/bin:$PATH" &&
flutter config --enable-web &&
flutter pub get &&
flutter build web --release
"""
publish = "build/web"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200