# Project Information
sonar.projectKey=Playverse
sonar.projectName=Playverse
sonar.projectVersion=1.0
sonar.organization=trusharpalminfotech

# SonarCloud Server URL (defaults to sonarcloud.io)
sonar.host.url=https://sonarcloud.io

# Quality Gate
sonar.qualitygate.wait=true

# Source Code
sonar.sources=lib

# Tests
sonar.tests=test

# Encoding
sonar.sourceEncoding=UTF-8

# Flutter Coverage (compatible with multiple Dart & Flutter SonarQube/SonarCloud plugins)
sonar.dart.lcov.reportPaths=coverage/lcov.info
sonar.flutter.coverage.reportPath=coverage/lcov.info
sonar.dart.lcov.reportPath=coverage/lcov.info

# Exclude Generated Files
sonar.exclusions=\
**/*.g.dart,\
**/*.freezed.dart,\
**/*.gen.dart,\
**/*.mocks.dart,\
**/*.config.dart,\
**/*.gr.dart,\
**/generated/**,\
**/build/**,\
**/.dart_tool/**,\
**/ios/Pods/**,\
**/android/.gradle/**,\
**/coverage/**,\
pubspec.lock

# Ignore generated files for coverage
sonar.coverage.exclusions=\
**/*.g.dart,\
**/*.freezed.dart,\
**/*.gen.dart,\
**/*.mocks.dart,\
**/*.config.dart,\
**/*.gr.dart,\
**/generated/**,\
**/build/**,\
**/.dart_tool/**,\
**/ios/Pods/**,\
**/android/.gradle/**,\
**/coverage/**

# Ignore generated files for duplication
sonar.cpd.exclusions=\
**/*.g.dart,\
**/*.freezed.dart,\
**/*.gen.dart,\
**/*.mocks.dart,\
**/*.config.dart,\
**/*.gr.dart,\
**/generated/**,\
**/build/**,\
**/.dart_tool/**,\
**/ios/Pods/**,\
**/android/.gradle/**,\
**/coverage/**
