default_platform(:ios)

platform :ios do
  desc "Get next TestFlight build number"

  lane :next_build_number do

    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_PRIVATE_KEY"]
    )

    version = get_version_number(
      xcodeproj: "Runner.xcodeproj"
    )

    begin
        latest = latest_testflight_build_number(
          api_key: api_key,
          app_identifier: "com.palm.gameverse",
          version: version,
          initial_build_number: 0
        )
    rescue
        latest = 0
    end
      
    next_build = latest + 1

    File.write("../next_build.txt", next_build.to_s)

    puts "NEXT_BUILD=#{next_build}"

  end
end