name: iOS CI Build

on:
  push:
    branches:
      - ios-app
  workflow_dispatch:

jobs:
  build_ios:
    name: Build Signed iOS IPA
    runs-on: macos-latest

    env:
      CERTIFICATE_PATH: /tmp/certificate.p12
      PP_PATH: /tmp/profile.mobileprovision
      KEYCHAIN_PATH: /tmp/app-signing.keychain-db
      EXPORT_OPTIONS_PATH: /tmp/ExportOptions.plist

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.7"
          channel: stable
          cache: true

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Flutter Analyze
        run: flutter analyze

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      # Decode Distribution Certificate
      - name: Decode Distribution Certificate
        run: |
          echo "${{ secrets.IOS_DISTRIBUTION_CERTIFICATE }}" | base64 --decode > $CERTIFICATE_PATH

      # Decode Provisioning Profile
      - name: Decode Provisioning Profile
        run: |
          echo "${{ secrets.IOS_PROVISIONING_PROFILE }}" | base64 --decode > $PP_PATH

      # Create Temporary Keychain
      - name: Create Keychain
        run: |
          security create-keychain -p "temp123" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "temp123" $KEYCHAIN_PATH

      # Import Certificate
      - name: Import Distribution Certificate
        run: |
          security import $CERTIFICATE_PATH \
            -k $KEYCHAIN_PATH \
            -P "${{ secrets.IOS_CERTIFICATE_PASSWORD }}" \
            -T /usr/bin/codesign

          security list-keychains -d user -s $KEYCHAIN_PATH
          security default-keychain -s $KEYCHAIN_PATH

      # Install Provisioning Profile
      - name: Install Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles/

      # Build Signed IPA
      - name: Build IPA
        run: flutter build ipa --release

      # Upload IPA
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa